# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 21:55
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookr', '0002_auto_20160525_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='email',
        ),
        migrations.RemoveField(
            model_name='people',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='people',
            name='hashpass',
        ),
        migrations.RemoveField(
            model_name='people',
            name='last_name',
        ),
        migrations.AddField(
            model_name='people',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
